package com.ecm.model;

import com.ecm.domain.PaymentStatus;

import lombok.Data;

@Data
public class PaymentDetails {

	 private String paymentId;
	    // Razorpay payment unique ID after successful payment.

	    private String razorpayPaymentLinkId;
	    // ID of the payment link generated by Razorpay for the transaction.

	    private String razorpayPaymentLinkReferenceId;
	    // Your internal reference ID to match Razorpay payment link with your order.

	    private String razorpayPaymentLinkStatus;
	    // Status of the payment link (CREATED, PAID, CANCELLED, EXPIRED).

	    private String razorpayPaymentIdZWSP;
	    // Sometimes Razorpay returns alternative payment ID (for specific workflows).
	    // Used when payment is completed through a special flow.

	    private PaymentStatus status;
	    // Current payment status from PaymentStatus enum (PENDING, PAID, FAILED, REFUNDED, etc.)
}
